### ISSUE TITLE
Issue regarding the schema in Issue #21

### ISSUE THREAD

**Issue by Gisonrg** [codebendercc/eratosthenes#36]
Regarding the original schema (#21), here are two issues I found today:
**1.Unique index on folder_name of _Version_** (#29)
Currently we are using relative path, so in each version we only store the folder name like "1.0.0" or "1.5.2". But this may violate the unique constraint. 
**Possible solution**: We either store the full path, or we remove the index.

**2.Unique index of version_id in _LibraryExample_** (#31)
What if there may be two or more example for this version? The unique constraint may be broken then.
**Possible solution**: we remove the index, or we set the constraint to be {id, version_id}

**Currently** I resolved the issue 1 by removing the index; resolved issue 2 by apply unique index on {id, version_id}. (see f66431b)

**Comment by Gisonrg** [comment]
@thngkaiyuan @bsmmoon

**Comment by bsmmoon** [comment]
2. What about we make (version_id, name) combination as a unique constraint? It will prevent duplicate name for the examples in that version. People will usually not make duplicate names, so I think preventing it makes sense. It will also help file system since we don't need to do something extra to resolve name duplicate.

**Comment by bsmmoon** [comment]
1
What about {library_id, version} since each library should hold one version of version?

**Comment by thngkaiyuan** [comment]
I agree with Seokmin on the first issue. I think putting a unique constraint on {library_id, folder_name} might be a better idea since that would dictate the unique relative path of a library version.

Regarding the second issue, I don't think the intent of the unique index was to prevent duplicate names from being created (the de-duplication process can be done elsewhere where it will be less costly). I seem to recall that the original intent was to allow us to retrieve all the examples pertaining to a Library version faster, thus the index. However, we might have been mistaken that this index should be unique. Therefore, I think the better solution for issue 2 is to change the unique index into a normal index without any constraint on its uniqueness.

**Comment by Gisonrg** [comment]
Fixed in be66943
